   throw er; // Unhandled 'error' event
      ^
DiscordAPIError[50035]: Invalid Form Body
58[APPLICATION_COMMANDS_DUPLICATE_NAME]: Application command names must be unique
    at handleErrors (/opt/render/project/src/node_modules/@discordjs/rest/dist/index.js:640:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async SequentialHandler.runRequest (/opt/render/project/src/node_modules/@discordjs/rest/dist/index.js:1021:23)
    at async SequentialHandler.queueRequest (/opt/render/project/src/node_modules/@discordjs/rest/dist/index.js:862:14)
    at async REST.request (/opt/render/project/src/node_modules/@discordjs/rest/dist/index.js:1387:22)
    at async ApplicationCommandManager.set (/opt/render/project/src/node_modules/discord.js/src/managers/ApplicationCommandManager.js:171:18)
    at async loadCommands (/opt/render/project/src/Handlers/commandHandler.js:39:3)
    at async Client.<anonymous> (file:///opt/render/project/src/index.js:81:3)
Emitted 'error' event on Client instance at:
    at emitUnhandledRejectionOrErr (node:events:401:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:92:21) {
  requestBody: {
    files: undefined,
    json: [
      {
        name: 'work',
        name_localizations: undefined,
        description: 'Work a job to earn chips (global, with cooldown).',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [],
        default_member_permissions: undefined,
        dm_permission: undefined
      },
      {
        name: 'weekly',
        name_localizations: undefined,
        description: 'Claim your big weekly chip reward (global).',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [],
        default_member_permissions: undefined,
        dm_permission: undefined
      },
      {
        name: 'wallet',
        name_localizations: undefined,
        description: "Check your (or another user's) global money and chips.",
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [
          {
            type: 6,
            name: 'user',
            name_localizations: undefined,
            name_localized: undefined,
            description: "Check someone else's wallet",
            description_localizations: undefined,
            description_localized: undefined,
            required: false,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          }
        ],
        default_member_permissions: undefined,
        dm_permission: undefined
      },
      {
        name: 'userinfo',
        name_localizations: undefined,
        description: 'Displays a detailed and dynamic user profile.',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [
          {
            type: 6,
            name: 'target',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Select a user to view information about.',
            description_localizations: undefined,
            description_localized: undefined,
            required: false,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          }
        ],
        default_member_permissions: undefined,
        dm_permission: undefined
      },
      {
        name: 'tts',
        name_localizations: undefined,
        description: 'Convert text to speech',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [
          {
            type: 3,
            name: 'text',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Text to convert to speech',
            description_localizations: undefined,
            description_localized: undefined,
            required: true,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          },
          {
            type: 3,
            name: 'lang',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Language code (default: en)',
            description_localizations: undefined,
            description_localized: undefined,
            required: false,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          }
        ],
        default_member_permissions: undefined,
        dm_permission: undefined
      },
      {
        name: 'trade',
        name_localizations: undefined,
        description: 'Send a secure chip trade request to another user.',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [
          {
            type: 6,
            name: 'user',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'User you want to trade with.',
            description_localizations: undefined,
            description_localized: undefined,
            required: true,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          },
          {
            type: 4,
            name: 'chips',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Chips you will offer.',
            description_localizations: undefined,
            description_localized: undefined,
            required: true,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: 1,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          }
        ],
        default_member_permissions: undefined,
        dm_permission: false
      },
      {
        name: 'tower',
        name_localizations: undefined,
        description: 'Climb a risky tower. Pick safe tiles, or lose everything.',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [
          {
            type: 4,
            name: 'bet',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Amount of chips to bet.',
            description_localizations: undefined,
            description_localized: undefined,
            required: true,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: 100,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          }
        ],
        default_member_permissions: undefined,
        dm_permission: false
      },
      {
        name: 'spotify',
        name_localizations: undefined,
        description: "Shows a user's current Spotify activity",
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [
          {
            type: 6,
            name: 'user',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'The user to check',
            description_localizations: undefined,
            description_localized: undefined,
            required: false,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          }
        ],
        default_member_permissions: undefined,
        dm_permission: undefined
      },
      {
        name: 'smoke',
        name_localizations: undefined,
        description: 'Light up a cigarette or join someone for a smoke.',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [
          {
            type: 6,
            name: 'user',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'User to smoke with',
            description_localizations: undefined,
            description_localized: undefined,
            required: false,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          }
        ],
        default_member_permissions: undefined,
        dm_permission: undefined
      },
      {
        name: 'slot',
        name_localizations: undefined,
        description: '🎰 Play slots and try your luck!',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [
          {
            type: 4,
            name: 'bet',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Amount of chips to bet',
            description_localizations: undefined,
            description_localized: undefined,
            required: true,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          }
        ],
        default_member_permissions: undefined,
        dm_permission: undefined
      },
      {
        name: 'shop',
        name_localizations: undefined,
        description: 'Browse and buy items from the advanced chip shop.',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [],
        default_member_permissions: undefined,
        dm_permission: false
      },
      {
        name: 'serverinfo',
        name_localizations: undefined,
        description: 'Displays a detailed overview of this server.',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [],
        default_member_permissions: undefined,
        dm_permission: undefined
      },
      {
        name: 'roulette',
        name_localizations: undefined,
        description: 'Play roulette: bet on red, black, a number, a dozen, or a column.',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [
          {
            type: 4,
            name: 'bet',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Amount to bet',
            description_localizations: undefined,
            description_localized: undefined,
            required: true,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          },
          {
            type: 3,
            name: 'choice',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Bet on: red, black, 0-36, dozen1, dozen2, dozen3, k1, k2, k3, even, odd',
            description_localizations: undefined,
            description_localized: undefined,
            required: true,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          }
        ],
        default_member_permissions: undefined,
        dm_permission: undefined
      },
      {
        name: 'plinko',
        name_localizations: undefined,
        description: 'Drop a chip on a Plinko board with risk-based multipliers.',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [
          {
            type: 4,
            name: 'bet',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Amount of chips to bet.',
            description_localizations: undefined,
            description_localized: undefined,
            required: true,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: 50,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          },
          {
            type: 3,
            name: 'risk',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Risk level of the board.',
            description_localizations: undefined,
            description_localized: undefined,
            required: true,
            autocomplete: undefined,
            choices: [Array],
            options: undefined,
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          }
        ],
        default_member_permissions: undefined,
        dm_permission: false
      },
      {
        name: 'ping',
        name_localizations: undefined,
        description: 'Show the bot’s current latency.',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [],
        default_member_permissions: undefined,
        dm_permission: undefined
      },
      {
        name: 'mines',
        name_localizations: undefined,
        description: '🪜 Play Mines: avoid the bombs and get rich!',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [
          {
            type: 4,
            name: 'bet',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Amount to bet',
            description_localizations: undefined,
            description_localized: undefined,
            required: true,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          },
          {
            type: 4,
            name: 'bombs',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Number of bombs (3-15)',
            description_localizations: undefined,
            description_localized: undefined,
            required: false,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          }
        ],
        default_member_permissions: undefined,
        dm_permission: undefined
      },
      {
        name: 'leaderboard',
        name_localizations: undefined,
        description: 'View the global chips leaderboard (all servers).',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [],
        default_member_permissions: undefined,
        dm_permission: undefined
      },
      {
        name: 'invite',
        name_localizations: undefined,
        description: 'Sends an invite link for the bot.',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [],
        default_member_permissions: undefined,
        dm_permission: undefined
      },
      {
        name: 'help',
        name_localizations: undefined,
        description: 'Browse all bot commands by category.',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [],
        default_member_permissions: undefined,
        dm_permission: undefined
      },
      {
        name: 'heist',
        name_localizations: undefined,
        description: 'Start a heist lobby where players can join via buttons.',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [],
        default_member_permissions: undefined,
        dm_permission: undefined
      },
      {
        name: 'dice',
        name_localizations: undefined,
        description: 'Bet on a dice roll with over/under or exact prediction.',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [
          {
            type: 4,
            name: 'bet',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Amount of chips to bet.',
            description_localizations: undefined,
            description_localized: undefined,
            required: true,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: 50,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          },
          {
            type: 3,
            name: 'type',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Prediction type.',
            description_localizations: undefined,
            description_localized: undefined,
            required: true,
            autocomplete: undefined,
            choices: [Array],
            options: undefined,
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          },
          {
            type: 4,
            name: 'target',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Target number (2–12 for over/under, 2–12 exact).',
            description_localizations: undefined,
            description_localized: undefined,
            required: true,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: 2,
            max_value: 12,
            min_length: undefined,
            max_length: undefined
          }
        ],
        default_member_permissions: undefined,
        dm_permission: false
      },
      {
        name: 'crypto',
        name_localizations: undefined,
        description: '💰 Get real-time crypto prices (3-API fallback).',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [
          {
            type: 3,
            name: 'coin',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Enter coin name or symbol (e.g. bitcoin, eth, solana)',
            description_localizations: undefined,
            description_localized: undefined,
            required: true,
            autocomplete: undefined,
            choices: [Array],
            options: undefined,
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          }
        ],
        default_member_permissions: undefined,
        dm_permission: undefined
      },
      {
        name: 'crash',
        name_localizations: undefined,
        description: 'Play a real-time crash game with multipliers.',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [
          {
            type: 4,
            name: 'bet',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Amount of chips to bet.',
            description_localizations: undefined,
            description_localized: undefined,
            required: true,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: 100,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          },
          {
            type: 10,
            name: 'auto',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Auto cashout at this multiplier (example: 2.5).',
            description_localizations: undefined,
            description_localized: undefined,
            required: false,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: 1.01,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          }
        ],
        default_member_permissions: undefined,
        dm_permission: false
      },
      {
        name: 'coinflip',
        name_localizations: undefined,
        description: 'Flip a coin and bet chips on heads or tails.',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [
          {
            type: 3,
            name: 'side',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Choose heads or tails.',
            description_localizations: undefined,
            description_localized: undefined,
            required: true,
            autocomplete: undefined,
            choices: [Array],
            options: undefined,
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          },
          {
            type: 4,
            name: 'bet',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'How many chips to bet.',
            description_localizations: undefined,
            description_localized: undefined,
            required: true,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          }
        ],
        default_member_permissions: undefined,
        dm_permission: undefined
      },
      {
        name: 'claim',
        name_localizations: undefined,
        description: 'Claim your daily chips (every 24h).',
        nsfw: undefined,
            name: 'risk',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Risk level of the board.',
            description_localizations: undefined,
            description_localized: undefined,
            required: true,
            autocomplete: undefined,
            choices: [Array],
            options: undefined,
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          }
        ],
        default_member_permissions: undefined,
        dm_permission: false
      },
      {
        name: 'ping',
        name_localizations: undefined,
        description: 'Show the bot’s current latency.',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [],
        default_member_permissions: undefined,
        dm_permission: undefined
      },
      {
        name: 'mines',
        name_localizations: undefined,
        description: '🪜 Play Mines: avoid the bombs and get rich!',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [
          {
            type: 4,
            name: 'bet',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Amount to bet',
            description_localizations: undefined,
            description_localized: undefined,
            required: true,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          },
          {
            type: 4,
            name: 'bombs',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Number of bombs (3-15)',
            description_localizations: undefined,
            description_localized: undefined,
            required: false,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          }
        ],
        default_member_permissions: undefined,
        dm_permission: undefined
      },
      {
        name: 'leaderboard',
        name_localizations: undefined,
        description: 'View the global chips leaderboard (all servers).',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [],
        default_member_permissions: undefined,
        dm_permission: undefined
      },
      {
        name: 'invite',
        name_localizations: undefined,
        description: 'Sends an invite link for the bot.',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [],
        default_member_permissions: undefined,
        dm_permission: undefined
      },
      {
        name: 'help',
        name_localizations: undefined,
        description: 'Browse all bot commands by category.',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [],
        default_member_permissions: undefined,
        dm_permission: undefined
      },
      {
        name: 'heist',
        name_localizations: undefined,
        description: 'Start a heist lobby where players can join via buttons.',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [],
        default_member_permissions: undefined,
        dm_permission: undefined
      },
      {
        name: 'dice',
        name_localizations: undefined,
        description: 'Bet on a dice roll with over/under or exact prediction.',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [
          {
            type: 4,
            name: 'bet',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Amount of chips to bet.',
            description_localizations: undefined,
            description_localized: undefined,
            required: true,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: 50,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          },
          {
            type: 3,
            name: 'type',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Prediction type.',
            description_localizations: undefined,
            description_localized: undefined,
            required: true,
            autocomplete: undefined,
            choices: [Array],
            options: undefined,
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          },
          {
            type: 4,
            name: 'target',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Target number (2–12 for over/under, 2–12 exact).',
            description_localizations: undefined,
            description_localized: undefined,
            required: true,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: 2,
            max_value: 12,
            min_length: undefined,
            max_length: undefined
          }
        ],
        default_member_permissions: undefined,
        dm_permission: false
      },
      {
        name: 'crypto',
        name_localizations: undefined,
        description: '💰 Get real-time crypto prices (3-API fallback).',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [
          {
            type: 3,
            name: 'coin',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Enter coin name or symbol (e.g. bitcoin, eth, solana)',
            description_localizations: undefined,
            description_localized: undefined,
            required: true,
            autocomplete: undefined,
            choices: [Array],
            options: undefined,
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          }
        ],
        default_member_permissions: undefined,
        dm_permission: undefined
      },
      {
        name: 'crash',
        name_localizations: undefined,
        description: 'Play a real-time crash game with multipliers.',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [
          {
            type: 4,
            name: 'bet',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Amount of chips to bet.',
            description_localizations: undefined,
            description_localized: undefined,
            required: true,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: 100,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          },
          {
            type: 10,
            name: 'auto',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Auto cashout at this multiplier (example: 2.5).',
            description_localizations: undefined,
            description_localized: undefined,
            required: false,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: 1.01,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          }
        ],
        default_member_permissions: undefined,
        dm_permission: false
      },
      {
        name: 'coinflip',
        name_localizations: undefined,
        description: 'Flip a coin and bet chips on heads or tails.',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [
          {
            type: 3,
            name: 'side',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Choose heads or tails.',
            description_localizations: undefined,
            description_localized: undefined,
            required: true,
            autocomplete: undefined,
            choices: [Array],
            options: undefined,
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          },
          {
            type: 4,
            name: 'bet',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'How many chips to bet.',
            description_localizations: undefined,
            description_localized: undefined,
            required: true,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          }
        ],
        default_member_permissions: undefined,
        dm_permission: undefined
      },
      {
        name: 'claim',
        name_localizations: undefined,
        description: 'Claim your daily chips (every 24h).',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [],
        default_member_permissions: undefined,
        dm_permission: undefined
      },
      {
        name: 'cases',
        name_localizations: undefined,
        description: 'Open loot cases with random chip rewards.',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [
          {
            type: 3,
            name: 'case',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Which case to open.',
            description_localizations: undefined,
            description_localized: undefined,
            required: true,
            autocomplete: undefined,
            choices: [Array],
            options: undefined,
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          }
        ],
        default_member_permissions: undefined,
        dm_permission: false
      },
      {
        name: 'buy',
        name_localizations: undefined,
        description: 'Buy an item from the shop by ID.',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [
          {
            type: 3,
            name: 'item',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'The itemId of the item you want to buy',
            description_localizations: undefined,
            description_localized: undefined,
            required: true,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          },
          {
            type: 4,
            name: 'quantity',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'How many to buy (default: 1)',
            description_localizations: undefined,
            description_localized: undefined,
            required: false,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: 1,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          }
        ],
        default_member_permissions: undefined,
        dm_permission: undefined
      },
      {
        name: 'botinfo',
        name_localizations: undefined,
        description: 'Displays detailed information about the bot.',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [],
        default_member_permissions: undefined,
        dm_permission: undefined
      },
      {
        name: 'blackjack',
        name_localizations: undefined,
        description: 'Play an advanced blackjack game for chips.',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [
          {
            type: 4,
            name: 'bet',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'How many chips to bet.',
            description_localizations: undefined,
            description_localized: undefined,
            required: true,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          }
        ],
        default_member_permissions: undefined,
        dm_permission: undefined
      },
      {
        name: 'beg',
        name_localizations: undefined,
        description: 'Beg for chips with a risky 50/50 chance (global).',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [],
        default_member_permissions: undefined,
        dm_permission: undefined
      },
      {
        name: 'avatar',
        name_localizations: undefined,
        description: "Sends a user's avatar in full resolution.",
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [
          {
            type: 6,
            name: 'user',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Select a user.',
            description_localizations: undefined,
            description_localized: undefined,
            required: false,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          }
        ],
        default_member_permissions: undefined,
        dm_permission: undefined
      },
      {
        name: 'afk',
        name_localizations: undefined,
        description: 'Set your AFK status',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [
          {
            type: 3,
            name: 'reason',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Reason for going AFK',
            description_localizations: undefined,
            description_localized: undefined,
            required: false,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          }
        ],
        default_member_permissions: undefined,
        dm_permission: undefined
      },
      {
        name: 'warn',
        name_localizations: undefined,
        description: 'Warn system commands',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [
          {
            type: 1,
            name: 'warn',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Warn a member.',
            description_localizations: undefined,
            description_localized: undefined,
            required: undefined,
            autocomplete: undefined,
            choices: undefined,
            options: [Array],
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          },
          {
            type: 1,
            name: 'warnings',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'List all warnings for a member.',
            description_localizations: undefined,
            description_localized: undefined,
            required: undefined,
            autocomplete: undefined,
            choices: undefined,
            options: [Array],
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          },
          {
            type: 1,
            name: 'delwarn',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Delete a warning by case ID.',
            description_localizations: undefined,
            description_localized: undefined,
            required: undefined,
            autocomplete: undefined,
            choices: undefined,
            options: [Array],
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          },
          {
            type: 1,
            name: 'clearwarns',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Clear all warnings for a member.',
            description_localizations: undefined,
            description_localized: undefined,
            required: undefined,
            autocomplete: undefined,
            choices: undefined,
            options: [Array],
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          }
        ],
        default_member_permissions: '1099511627776',
        dm_permission: undefined
      },
      {
        name: 'voicemaster',
        name_localizations: undefined,
        description: 'VoiceMaster setup and management system',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [
          {
            type: 1,
            name: 'setup',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Set up VoiceMaster system for your server',
            description_localizations: undefined,
            description_localized: undefined,
            required: undefined,
            autocomplete: undefined,
            choices: undefined,
            options: [],
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          },
          {
            type: 1,
            name: 'remove',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Remove VoiceMaster system from your server',
            description_localizations: undefined,
            description_localized: undefined,
            required: undefined,
            autocomplete: undefined,
            choices: undefined,
            options: [],
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          },
          {
            type: 1,
            name: 'interface',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Resend the VoiceMaster control panel',
            description_localizations: undefined,
            description_localized: undefined,
            required: undefined,
            autocomplete: undefined,
            choices: undefined,
            options: [],
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          }
        ],
        default_member_permissions: '8',
        dm_permission: undefined
      },
      {
        name: 'unmute',
        name_localizations: undefined,
        description: 'Unmute a member',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [
          {
            type: 6,
            name: 'user',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Select member to unmute',
            description_localizations: undefined,
            description_localized: undefined,
            required: true,
            autocomplete: undefined,
            description_localized: undefined,
            required: true,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          },
          {
            type: 3,
            name: 'duration',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'How long? Example: 10m, 1h, 1d',
            description_localizations: undefined,
            description_localized: undefined,
            required: true,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          },
          {
            type: 3,
            name: 'reason',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Reason for the timeout',
            description_localizations: undefined,
            description_localized: undefined,
            required: false,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: undefined,
            name: 'risk',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Risk level of the board.',
            description_localizations: undefined,
            description_localized: undefined,
            required: true,
            autocomplete: undefined,
            choices: [Array],
            options: undefined,
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          }
        ],
        default_member_permissions: undefined,
        dm_permission: false
      },
      {
        name: 'ping',
        name_localizations: undefined,
        description: 'Show the bot’s current latency.',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [],
        default_member_permissions: undefined,
        dm_permission: undefined
      },
      {
        name: 'mines',
        name_localizations: undefined,
        description: '🪜 Play Mines: avoid the bombs and get rich!',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [
          {
            type: 4,
            name: 'bet',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Amount to bet',
            description_localizations: undefined,
            description_localized: undefined,
            required: true,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          },
          {
            type: 4,
            name: 'bombs',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Number of bombs (3-15)',
            description_localizations: undefined,
            description_localized: undefined,
            required: false,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          }
        ],
        default_member_permissions: undefined,
        dm_permission: undefined
      },
      {
        name: 'leaderboard',
        name_localizations: undefined,
        description: 'View the global chips leaderboard (all servers).',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [],
        default_member_permissions: undefined,
        dm_permission: undefined
      },
      {
        name: 'invite',
        name_localizations: undefined,
        description: 'Sends an invite link for the bot.',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [],
        default_member_permissions: undefined,
        dm_permission: undefined
      },
      {
        name: 'help',
        name_localizations: undefined,
        description: 'Browse all bot commands by category.',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [],
        default_member_permissions: undefined,
        dm_permission: undefined
      },
      {
        name: 'heist',
        name_localizations: undefined,
        description: 'Start a heist lobby where players can join via buttons.',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [],
        default_member_permissions: undefined,
        dm_permission: undefined
      },
      {
        name: 'dice',
        name_localizations: undefined,
        description: 'Bet on a dice roll with over/under or exact prediction.',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [
          {
            type: 4,
            name: 'bet',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Amount of chips to bet.',
            description_localizations: undefined,
            description_localized: undefined,
            required: true,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: 50,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          },
          {
            type: 3,
            name: 'type',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Prediction type.',
            description_localizations: undefined,
            description_localized: undefined,
            required: true,
            autocomplete: undefined,
            choices: [Array],
            options: undefined,
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          },
          {
            type: 4,
            name: 'target',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Target number (2–12 for over/under, 2–12 exact).',
            description_localizations: undefined,
            description_localized: undefined,
            required: true,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: 2,
            max_value: 12,
            min_length: undefined,
            max_length: undefined
          }
        ],
        default_member_permissions: undefined,
        dm_permission: false
      },
      {
        name: 'crypto',
        name_localizations: undefined,
        description: '💰 Get real-time crypto prices (3-API fallback).',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [
          {
            type: 3,
            name: 'coin',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Enter coin name or symbol (e.g. bitcoin, eth, solana)',
            description_localizations: undefined,
            description_localized: undefined,
            required: true,
            autocomplete: undefined,
            choices: [Array],
            options: undefined,
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          }
        ],
        default_member_permissions: undefined,
        dm_permission: undefined
      },
      {
        name: 'crash',
        name_localizations: undefined,
        description: 'Play a real-time crash game with multipliers.',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [
          {
            type: 4,
            name: 'bet',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Amount of chips to bet.',
            description_localizations: undefined,
            description_localized: undefined,
            required: true,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: 100,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          },
          {
            type: 10,
            name: 'auto',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Auto cashout at this multiplier (example: 2.5).',
            description_localizations: undefined,
            description_localized: undefined,
            required: false,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: 1.01,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          }
        ],
        default_member_permissions: undefined,
        dm_permission: false
      },
      {
        name: 'coinflip',
        name_localizations: undefined,
        description: 'Flip a coin and bet chips on heads or tails.',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [
          {
            type: 3,
            name: 'side',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Choose heads or tails.',
            description_localizations: undefined,
            description_localized: undefined,
            required: true,
            autocomplete: undefined,
            choices: [Array],
            options: undefined,
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          },
          {
            type: 4,
            name: 'bet',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'How many chips to bet.',
            description_localizations: undefined,
            description_localized: undefined,
            required: true,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          }
        ],
        default_member_permissions: undefined,
        dm_permission: undefined
      },
      {
        name: 'claim',
        name_localizations: undefined,
        description: 'Claim your daily chips (every 24h).',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [],
        default_member_permissions: undefined,
        dm_permission: undefined
      },
      {
        name: 'cases',
        name_localizations: undefined,
        description: 'Open loot cases with random chip rewards.',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [
          {
            type: 3,
            name: 'case',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Which case to open.',
            description_localizations: undefined,
            description_localized: undefined,
            required: true,
            autocomplete: undefined,
            choices: [Array],
            options: undefined,
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          }
        ],
        default_member_permissions: undefined,
        dm_permission: false
      },
      {
        name: 'buy',
        name_localizations: undefined,
        description: 'Buy an item from the shop by ID.',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [
          {
            type: 3,
            name: 'item',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'The itemId of the item you want to buy',
            description_localizations: undefined,
            description_localized: undefined,
            required: true,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          },
          {
            type: 4,
            name: 'quantity',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'How many to buy (default: 1)',
            description_localizations: undefined,
            description_localized: undefined,
            required: false,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: 1,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          }
        ],
        default_member_permissions: undefined,
        dm_permission: undefined
      },
      {
        name: 'botinfo',
        name_localizations: undefined,
        description: 'Displays detailed information about the bot.',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [],
        default_member_permissions: undefined,
        dm_permission: undefined
      },
      {
            required: false,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          }
        ],
        default_member_permissions: '2',
        dm_permission: undefined
      },
      {
        name: 'give',
        name_localizations: undefined,
        description: 'Give chips to a user (Bot owner only).',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [
          {
            type: 6,
            name: 'target',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'User to give chips',
            description_localizations: undefined,
            description_localized: undefined,
            required: true,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          },
          {
            type: 4,
            name: 'amount',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Amount of chips',
            description_localizations: undefined,
            description_localized: undefined,
            required: true,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          }
        ],
        default_member_permissions: undefined,
        dm_permission: undefined
      },
      {
        name: 'editsnipe',
        name_localizations: undefined,
        description: 'Shows the last edited messages in this channel.',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [],
        default_member_permissions: undefined,
        dm_permission: undefined
      },
      {
        name: 'ban',
        name_localizations: undefined,
        description: 'Ban a member from the guild by mention or user ID',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [
          {
            type: 6,
            name: 'target',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'The member to ban',
            description_localizations: undefined,
            description_localized: undefined,
            required: false,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          },
          {
            type: 3,
            name: 'userid',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'User ID to ban',
            description_localizations: undefined,
            description_localized: undefined,
            required: false,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          },
          {
            type: 3,
            name: 'reason',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Reason for banning',
            description_localizations: undefined,
            description_localized: undefined,
            required: false,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          }
        ],
        default_member_permissions: '4',
        dm_permission: undefined
      },
      {
        name: 'altscanner',
        name_localizations: undefined,
        description: 'Scan a user for potential alt accounts',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [
          {
            type: 6,
            name: 'user',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'The user to scan for potential alts',
            description_localizations: undefined,
            description_localized: undefined,
            required: true,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          },
          {
            type: 10,
            name: 'threshold',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Similarity threshold (0.0-1.0, default 0.5)',
            description_localizations: undefined,
            description_localized: undefined,
            required: false,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: 0.1,
            max_value: 1,
            min_length: undefined,
            max_length: undefined
          }
        ],
        default_member_permissions: '1099511627776',
        dm_permission: undefined
      },
      {
        name: 'admin-role',
        name_localizations: undefined,
        description: 'Add or remove a role from a user (Developer only)',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [
          {
            type: 1,
            name: 'add',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Give a role to a user',
            description_localizations: undefined,
            description_localized: undefined,
            required: undefined,
            autocomplete: undefined,
            choices: undefined,
            options: [Array],
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          },
          {
            type: 1,
            name: 'remove',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Remove a role from a user',
            description_localizations: undefined,
            description_localized: undefined,
            required: undefined,
            autocomplete: undefined,
            choices: undefined,
            options: [Array],
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          }
        ],
        default_member_permissions: undefined,
        dm_permission: undefined
      },
      {
        name: 'slap',
        name_localizations: undefined,
        description: 'Slap someone 😳',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [
          {
            type: 6,
            name: 'user',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Who do you want to slap?',
            description_localizations: undefined,
            description_localized: undefined,
            required: true,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          }
        ],
        default_member_permissions: undefined,
        dm_permission: undefined
      },
      {
        name: 'ship',
        name_localizations: undefined,
        description: 'Ship two users together 💕',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [
          {
            type: 6,
            name: 'user1',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'First user',
            description_localizations: undefined,
            description_localized: undefined,
            required: true,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          },
          {
            type: 6,
            name: 'user2',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Second user',
            description_localizations: undefined,
            description_localized: undefined,
            required: true,
            autocomplete: undefined,
            choices: undefined,
            options: undefined,
            channel_types: undefined,
            min_value: undefined,
            max_value: undefined,
            min_length: undefined,
            max_length: undefined
          }
        ],
        default_member_permissions: undefined,
        dm_permission: undefined
      },
      {
        name: 'quote',
        name_localizations: undefined,
        description: 'Get a random inspirational quote.',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [],
        default_member_permissions: undefined,
        dm_permission: undefined
      },
      {
        name: 'minigame',
        name_localizations: undefined,
        description: 'Play a fun mini-game with yourself or a friend!',
        nsfw: undefined,
        description_localizations: undefined,
        type: 1,
        options: [
          {
            type: 3,
            name: 'game',
            name_localizations: undefined,
            name_localized: undefined,
            description: 'Choose a mini-game',
            description_localizations: undefined,
            description_localized: undefined,
            required: true,
            autocomplete: undefined,
            choices: [Array],
            options: undefined,
            channel_types: undefined,
